server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  h2:
    console.enabled: true
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  application:
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    #    properties:
    #      hibernate:
    #        dialect: org.hibernate.dialect.PostgreSQLDialect
    #        format_sql: true
    #    name: customer
    #    hibernate:
    #      ddl-auto: create
    show-sql: false
  datasource:
    driverClassName: org.h2.Driver
    initialize: true
    username: sa
    password: password
    #    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.databaseName}
    url: jdbc:h2:mem:imagedb
#    dockerContainerName: postgresqldb
#    host: 172.17.0.2
#    localhost: localhost
#    port: 5432
#    databaseName: playerdb


#    spring.datasource.url=jdbc:h2:mem:testdb
#    spring.datasource.driverClassName=org.h2.Driver
#    spring.datasource.username=sa
#    spring.datasource.password=password
#    spring.jpa.database-platform=org.hibernate.dialect.H2Dialect